# Example here : https://github.com/GitGuardian/ggshield/blob/main/.gitguardian.example.yml
# Required, otherwise ggshield considers the file to use the deprecated v1 format
version: 2
#
# Set to true if the desired exit code for the CLI is always 0, otherwise the
# exit code will be 1 if incidents are found.
# The environment variable GITGUARDIAN_EXIT_ZERO=true can also be used toggle this behavior.
exit-zero: false # default: false
#
verbose: false # default: false
#
# The dashboard URL of the instance
instance: https://dashboard.gitguardian.com # default: https://dashboard.gitguardian.com
#
# Maximum commits to scan in a hook.
max-commits-for-hook: 50 # default: 50
#
# Accept self-signed certificates for the API.
allow-self-signed: false # default: false
#
secret:
  # Exclude files and paths by globbing
  ignored-paths:
    - "**/README.md"
    - "back_node/tests/**"
    - "clientDiscord/tests/**"
