name: "[FLUTTER] APK Create"
run-name: "[FLUTTER] APK Create : ${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on:
  push:
    paths:
      - client_flutter/**
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.13.2'
          channel: stable
      - name: Create env file
        working-directory: ./client_flutter
        run: |
          touch .env
          echo BASEURL=${{ secrets.API_BASEURL }} >> .env
          echo MODE=DEV >> .env
          cat .env
          ls -a
      - name: get package
        working-directory: ./client_flutter
        run: |
          flutter pub get
      - name: launch Test
        continue-on-error: true
        working-directory: ./client_flutter
        run : |
          flutter test
      # Create key.properties file
      - name: Create key.properties file
        working-directory: ./client_flutter/android
        run: |
          touch key.properties
          echo storePassword=${{secrets.FLUTTER_KEY_PASSWORD}} >> key.properties
          echo keyPassword=${{secrets.FLUTTER_KEY_PASSWORD}} >> key.properties
          echo keyAlias=${{secrets.FLUTTER_KEY_ALIAS}} >> key.properties
          echo "${{secrets.FLUTTER_KEY_STORE}}" > upload-keystore.encoded
          base64 -d -i upload-keystore.encoded > ~/upload-keystore.jks
          echo storeFile=~/upload-keystore.jks >> key.properties
          cat key.properties
          ls -a
      - name: build apk
        working-directory: ./client_flutter
        run : |
          flutter build apk --no-tree-shake-icons
      
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: client_flutter/build/app/outputs/flutter-apk/app-release.apk