name: "[FLUTTER] APK Create"
run-name: "[FLUTTER] APK Create : ${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on:
  push:
    # branches: 
    #   - developFlutter
    # paths:
    #   - app_flutter/**
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.13.2'
          channel: stable
      - name: Create env file
        working-directory: ./app_flutter
        run: |
          touch .env
          echo BASEURL=${{ secrets.API_BASEURL }} >> .env
          echo MODE=DEV >> .env
          cat .env
          ls -a
      - name: get package
        working-directory: ./app_flutter
        run: |
          flutter pub get
      - name: launch Test
        working-directory: ./app_flutter
        run : |
          flutter test
      - name: build apk
        working-directory: ./app_flutter
        run : |
          flutter build apk --debug